GET http://localhost:8080/incidents/1/attachments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZpZXdlckB0ZXN0LmNvbSIsImV4cCI6MTc4MDc1NzY2OCwicm9sZSI6IlZpZXdlciIsInVzZXJfaWQiOjR9.aPP0ylFU92BVV_iwg3whgyG7T0A-mJXeGkSLD4SVi1M
